package com.yanll.auth.service.domain;

import com.yanll.framework.facade.domain.DTOEntity;

/*
 * 当前文件为MybatisGenerator生成的DTO，请勿修改。
 */
public class MenuBeanDTO extends DTOEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.portal_id
     *
     * @mbg.generated
     */
    private Integer portalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_code
     *
     * @mbg.generated
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.menu_params
     *
     * @mbg.generated
     */
    private String menuParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.idx
     *
     * @mbg.generated
     */
    private Long idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.enabled
     *
     * @mbg.generated
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_menu.editable
     *
     * @mbg.generated
     */
    private Integer editable;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.id
     *
     * @return the value of m_menu.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.id
     *
     * @param id the value for m_menu.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.portal_id
     *
     * @return the value of m_menu.portal_id
     * @mbg.generated
     */
    public Integer getPortalId() {
        return portalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.portal_id
     *
     * @param portalId the value for m_menu.portal_id
     * @mbg.generated
     */
    public void setPortalId(Integer portalId) {
        this.portalId = portalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.parent_id
     *
     * @return the value of m_menu.parent_id
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.parent_id
     *
     * @param parentId the value for m_menu.parent_id
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.url
     *
     * @return the value of m_menu.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.url
     *
     * @param url the value for m_menu.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_code
     *
     * @return the value of m_menu.menu_code
     * @mbg.generated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_code
     *
     * @param menuCode the value for m_menu.menu_code
     * @mbg.generated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_name
     *
     * @return the value of m_menu.menu_name
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_name
     *
     * @param menuName the value for m_menu.menu_name
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.menu_params
     *
     * @return the value of m_menu.menu_params
     * @mbg.generated
     */
    public String getMenuParams() {
        return menuParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.menu_params
     *
     * @param menuParams the value for m_menu.menu_params
     * @mbg.generated
     */
    public void setMenuParams(String menuParams) {
        this.menuParams = menuParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.icon
     *
     * @return the value of m_menu.icon
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.icon
     *
     * @param icon the value for m_menu.icon
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.idx
     *
     * @return the value of m_menu.idx
     * @mbg.generated
     */
    public Long getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.idx
     *
     * @param idx the value for m_menu.idx
     * @mbg.generated
     */
    public void setIdx(Long idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.enabled
     *
     * @return the value of m_menu.enabled
     * @mbg.generated
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.enabled
     *
     * @param enabled the value for m_menu.enabled
     * @mbg.generated
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_menu.editable
     *
     * @return the value of m_menu.editable
     * @mbg.generated
     */
    public Integer getEditable() {
        return editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_menu.editable
     *
     * @param editable the value for m_menu.editable
     * @mbg.generated
     */
    public void setEditable(Integer editable) {
        this.editable = editable;
    }
}