package com.yanll.auth.service.domain;

import com.yanll.framework.facade.domain.DTOEntity;

/*
* 当前文件为MybatisGenerator生成的DTO，请勿修改。
*/
public class PermissionGroupRelBeanDTO extends DTOEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_permission_group_rel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_permission_group_rel.group_id
     *
     * @mbg.generated
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_permission_group_rel.permission_id
     *
     * @mbg.generated
     */
    private Long permissionId;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_permission_group_rel.id
     *
     * @return the value of m_permission_group_rel.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_permission_group_rel.id
     *
     * @param id the value for m_permission_group_rel.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_permission_group_rel.group_id
     *
     * @return the value of m_permission_group_rel.group_id
     *
     * @mbg.generated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_permission_group_rel.group_id
     *
     * @param groupId the value for m_permission_group_rel.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_permission_group_rel.permission_id
     *
     * @return the value of m_permission_group_rel.permission_id
     *
     * @mbg.generated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_permission_group_rel.permission_id
     *
     * @param permissionId the value for m_permission_group_rel.permission_id
     *
     * @mbg.generated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}