package com.yanll.auth.service.domain;

import com.yanll.framework.data.domain.POEntity;

/*
 * 当前文件为MybatisGenerator自动生成，重新生成时会被覆盖，请勿修改！（表结构变化时请重新生成）
 * table:m_user_permission_rel
 */
public class UserPermissionRelBean extends POEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_permission_rel.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_permission_rel.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user_permission_rel.permission_id
     *
     * @mbg.generated
     */
    private Long permissionId;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_permission_rel.id
     *
     * @return the value of m_user_permission_rel.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_permission_rel.id
     *
     * @param id the value for m_user_permission_rel.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_permission_rel.user_id
     *
     * @return the value of m_user_permission_rel.user_id
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_permission_rel.user_id
     *
     * @param userId the value for m_user_permission_rel.user_id
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_user_permission_rel.permission_id
     *
     * @return the value of m_user_permission_rel.permission_id
     * @mbg.generated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_user_permission_rel.permission_id
     *
     * @param permissionId the value for m_user_permission_rel.permission_id
     * @mbg.generated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}